apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fcg
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: fcg
data:
  init.sql: |
    CREATE DATABASE catalogdb;
    CREATE DATABASE notificationsdb;
    CREATE DATABASE paymentsdb;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: "fcg"
            - name: POSTGRES_PASSWORD
              value: "fcg123"
            - name: POSTGRES_DB
              value: "fcgdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init
          configMap:
            name: postgres-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fcg
spec:
  selector: { app: postgres }
  ports:
    - port: 5432
      targetPort: 5432
